"""Constants for propensity_matching library."""
MINIMUM_DF_COUNT = 4000
MINIMUM_POS_COUNT = 1000

UTIL_BOOST_THRESH_1 = MINIMUM_POS_COUNT
UTIL_BOOST_THRESH_2 = MINIMUM_DF_COUNT
UTIL_BOOST_THRESH_3 = 50000

SAMPLES_PER_FEATURE = 100

SMALL_MATCH_THRESHOLD = 3000**3


