"""Constants for propensity_matching library."""
NO_IMPACT_THRESHOLD_COUNT = 2000
NAIVE_THRESHOLD_COUNT = 5000

UTIL_BOOST_THRESH_1 = NO_IMPACT_THRESHOLD_COUNT
UTIL_BOOST_THRESH_2 = NAIVE_THRESHOLD_COUNT
UTIL_BOOST_THRESH_3 = 50000

SAMPLES_PER_FEATURE = 100

SMALL_MATCH_THRESHOLD = 10000**3

MINIMUM_DF_COUNT = 1000
MINIMUM_POS_COUNT = 200
